### ISSUE TITLE
5120 scan entries

### ISSUE THREAD

**Issue by Andrey057835** [CloverHackyColor/CloverBootloader#224]
Hello.

I have laptop asus fx504-gm, and i'm stuck on scan entries here is log
[debug.log](https://github.com/CloverHackyColor/CloverBootloader/files/5096903/debug.log)

**Comment by Andrey057835** [comment]
Help Please

**Comment by asgmeonerandom** [comment]
what are you trying to install? where it fails? add screenshot!

**Comment by Andrey057835** [comment]
> what are you trying to install? where it fails? add screenshot!

 I tried instal catalina and high sierra(clover), on different version of clover the same error #
![IMG_20200820_090732](https://user-images.githubusercontent.com/69908201/90712444-de580800-e2c4-11ea-8e33-db287db330b9.jpg)

**Comment by bfitzgit23** [comment]
I’m getting stuck here using Big Sur beta 5, no idea why nor how to Troubleshoot and fix it

**Comment by asgmeonerandom** [comment]
Paste what he says here https://github.com/CloverHackyColor/CloverBootloader/issues/8#issuecomment-544355811

**Comment by Andrey057835** [comment]
> Paste what he says here [#8 (comment)](https://github.com/CloverHackyColor/CloverBootloader/issues/8#issuecomment-544355811)

did you mean debug? in first post it

**Comment by asgmeonerandom** [comment]
> > Paste what he says here [#8 (comment)](https://github.com/CloverHackyColor/CloverBootloader/issues/8#issuecomment-544355811)
> 
> did you mean debug? in first post it

yep

**Comment by Andrey057835** [comment]
> > > Paste what he says here [#8 (comment)](https://github.com/CloverHackyColor/CloverBootloader/issues/8#issuecomment-544355811)
> > 
> > 
> > did you mean debug? in first post it
> 
> yep

[debug (1).log](https://github.com/CloverHackyColor/CloverBootloader/files/5106694/debug.1.log)

**Comment by asgmeonerandom** [comment]
> > > > Paste what he says here [#8 (comment)](https://github.com/CloverHackyColor/CloverBootloader/issues/8#issuecomment-544355811)
> > > 
> > > 
> > > did you mean debug? in first post it
> > 
> > 
> > yep
> 
> [debug (1).log](https://github.com/CloverHackyColor/CloverBootloader/files/5106694/debug.1.log)

your last message is "No AppleSMC Controller" , you should google or post in forum like insanelymac for support.

**Comment by Andrey057835** [comment]
> > > > > Paste what he says here [#8 (comment)](https://github.com/CloverHackyColor/CloverBootloader/issues/8#issuecomment-544355811)
> > > > 
> > > > 
> > > > did you mean debug? in first post it
> > > 
> > > 
> > > yep
> > 
> > 
> > [debug (1).log](https://github.com/CloverHackyColor/CloverBootloader/files/5106694/debug.1.log)
> 
> your last message is "No AppleSMC Controller" , you should google or post in forum like insanelymac for support.

Ok, thanks

**Comment by SergeySlice** [comment]
Resolved in 5122.

**Comment by Andrey057835** [comment]
> Resolved in 5122.

Not resolved,  i install macos on 5120, and then many times it works but one time it show me again scan entries when i update clover to 5121, i tried load my working 5120 clover but nothing changed

**Comment by Andrey057835** [comment]
Resolved problem, but here is New
![IMG_20200904_194508](https://user-images.githubusercontent.com/69908201/92246274-58a0a300-eee7-11ea-9e63-d813c4ba894a.jpg)

**Comment by SergeySlice** [comment]
New problem - new ticket.
Don't forget to show config.plist and debug.log
