### ISSUE TITLE
[SOLVED] Clover disregards GUI Custom Tool Argument

### ISSUE THREAD

**Issue by LeeBinder** [CloverHackyColor/CloverBootloader#376]
verified not working not just with latest Clover 5131 but at least all the way down to r5108. `ControlMsrE2.efi` runs but complains that an argument is required but missing even though it indeed _is_ defined in config.plist:
![Screenshot_1](https://user-images.githubusercontent.com/39203497/110465075-412fb600-80d4-11eb-83a9-040603d0f1d2.jpg)
after key press:
![Screenshot_2 after key pressed](https://user-images.githubusercontent.com/39203497/110465122-51479580-80d4-11eb-9c1b-c838ca76d19c.jpg)

```
<dict>
	<key>Volume</key>
	<string>\</string>
	<key>Path</key>
	<string>\EFI\Clover\Tools\ControlMsrE2.efi</string>
	<key>Arguments</key>
	<string>unlock</string>
	<key>FullTitle</key>
	<string>1-ControlMsrE2</string>
	<key>Hotkey</key>
	<string></string>
	<key>Hidden</key>
	<false/>
	<key>Disable</key>
	<false/>
	<key>Ignore</key>
	<false/>
</dict>
```
Below how's it's supposed to looke like - photo of `ControlMsrE2.efi` w/ arg `unlock` evoked from OC:
![Screenshot](https://user-images.githubusercontent.com/39203497/110465517-c7e49300-80d4-11eb-827f-38262c063382.jpg)

The parameter must follow `ControlMsrE2.efi` without a preceding `-` only divided by a space, like this:

`ControlMsrE2.efi unlock`

I also tried `<string>"unlock"</string>` and `<string>'unlock'</string>`
and also
`<string> unlock</string>` , `<string> "unlock"</string>` and `<string> 'unlock'</string>`

Here's the .zip with everything you need so you can replicate the bug in your setup: [GUI Custom Tool Arguments disregarded.zip](https://github.com/CloverHackyColor/CloverBootloader/files/6104765/GUI.Custom.Tool.Arguments.disregarded.zip)

**Comment by LeeBinder** [comment]
tested all the way down to r5108 - same thing. Must be an old bug.

**Comment by LeeBinder** [comment]
source code (thanks to cecekpawon for the pointer): https://github.com/zhen-zen/OpenCorePkg/tree/ControlMsrE2/Application/ControlMsrE2

**Comment by LeeBinder** [comment]
on Mar 21, 2021, 7:21 AM GMT+1 @SergeySlice [wrote](https://github.com/CloverHackyColor/CloverBootloader/issues/377#issuecomment-803520230):
> ControlMsrE2.efi works as well in Clover 5131 with Shell provided with the Clover.
> ![IMG_0480](https://user-images.githubusercontent.com/485515/111895895-cb5a1180-8a26-11eb-82ee-2cdbb7912bd8.jpeg)

yes, it works fine if run via shell. What happens when you run it from `Tools` on your computer - does it work from there for you, either with any of the 3 arguments
```
<dict>
	<key>Volume</key>
	<string>\</string>
	<key>Path</key>
	<string>\EFI\Clover\Tools\ControlMsrE2.efi</string>
	<key>Arguments</key>
	<string>unlock</string>
	<key>FullTitle</key>
	<string>1-ControlMsrE2</string>
	<key>Hotkey</key>
	<string></string>
	<key>Hidden</key>
	<false/>
	<key>Disable</key>
	<false/>
	<key>Ignore</key>
	<false/>
</dict>
```
or even with empty `<key>Arguments</key>` `<string></string>`?

**Comment by jief666** [comment]
Should work now with the latest commit, or this efi : [CLOVERX64.efi.zip](https://github.com/CloverHackyColor/CloverBootloader/files/6184373/CLOVERX64.efi.zip)

Please test. If works, close this issue please.

**Comment by LeeBinder** [comment]
@jief666 sorry but no, error persists here. Additionally I even just tried the [latest ControlMsrE2.efi compile](https://github.com/acidanthera/OpenCorePkg/suites/2312082823/artifacts/48544825), both release and debug version.

I verified Clover really did boot from the `CLOVERX64.efi` from your link, renamed and copied to `EFI/BOOT/BOOTX64.efi`:

![screenshot0](https://user-images.githubusercontent.com/39203497/112051220-f5f4b900-8b51-11eb-9597-d264b8aaf025.png)

I even tried the trick which works with Brummbär's original CFGlock.efi - as an intermediate step first open my Laptop's UEFI BIOS boot menu, but still no-go.

Does `ControlMsrE2.efi` work for you via tools? If so, maybe you could zip and attach your EFI folder - (minus) themes and SMBIOS data in config.plist.

**Comment by jief666** [comment]
Send your debug.log...

**Comment by LeeBinder** [comment]
sure - can do tomorrow - have to leave right this second

**Comment by LeeBinder** [comment]
> Send your debug.log...

here you go -> [2021-3-23_20-27_BOOTX64.EFI.log.zip](https://github.com/CloverHackyColor/CloverBootloader/files/6192259/2021-3-23_20-27_BOOTX64.EFI.log.zip)

also preboot.log, for what it might be worth -> [preboot.log.zip](https://github.com/CloverHackyColor/CloverBootloader/files/6192274/preboot.log.zip)

**Comment by jief666** [comment]
That is the log for when you boot macOS. I'd like the log when you tried to boot ControlMsrE2.efi.

**Comment by jief666** [comment]
Also, in that log, I don't see any custom tool "ControlMsrE2.efi".

**Comment by LeeBinder** [comment]
> Also, in that log, I don't see any custom tool "ControlMsrE2.efi".

![screenshot](https://user-images.githubusercontent.com/39203497/112213576-839dda80-8c1e-11eb-8a7f-ff3b4b9e9939.jpg)

[config.plist.zip](https://github.com/CloverHackyColor/CloverBootloader/files/6192550/config.plist.zip)

> That is the log for when you boot macOS. I'd like the log when you tried to boot ControlMsrE2.efi.

this time I invoked both via Clover > tools, `ControlMsrE2.efi` and `ControlMsrE2_debug.efi` while Clover > Boot > Debug is enabled - hopefully efi tools log into that debug log, too.

[2021-3-23_21-18_BOOTX64.EFI.log.zip](https://github.com/CloverHackyColor/CloverBootloader/files/6192565/2021-3-23_21-18_BOOTX64.EFI.log.zip)

**Comment by jief666** [comment]
Thanks, your config.plist and log were helpful.
I didn't realize it was a custom tool and not a custom entry.
Should work now. Compile last commit or : [CLOVERX64.efi.zip](https://github.com/CloverHackyColor/CloverBootloader/files/6192817/CLOVERX64.efi.zip)

**Comment by LeeBinder** [comment]
> I didn't realize it was a custom tool and not a custom entry.

my bad - should've set the issue title to double-size and red .. ;)

> Should work now. Compile last commit or : CLOVERX64.efi.zip

YES, you ROCK as usual - finally the arg is being passed over - great job!

Clover still needs the UEFI BIOS boot menu to be invoked first to initiate the MSR E2 register so that both, `ControlMsrE2.efi` and `CFGLock.efi` find it if called via Clover, but oh well, that's a minor oddity in contrast to OC. Fair enough/ fine for now.

Thanks again @jief666 for solving this Bug!

**Comment by jief666** [comment]
> my bad - should've set the issue title to double-size and red .. ;)

Of course NOT. I never used Custom tool and I misinterpreted it as a tool configured as a custom entry. My bad.

> Clover still needs the UEFI BIOS boot menu to be invoked first

Not sure to understand that. If you'd like an improvement, it maybe possible...

**Comment by LeeBinder** [comment]
> Not sure to understand that. If you'd like an improvement, it maybe possible...

I explained it [here](https://github.com/LeeBinder/Asus-Vivobook-S510UA-Hackintosh/blob/main/README.md/#user-content-msr-unlock-clover)

**Comment by jief666** [comment]
> I explained it [here](https://github.com/LeeBinder/Asus-Vivobook-S510UA-Hackintosh/blob/main/README.md/#user-content-msr-unlock-clover).
What you explained here is now possible again, right ?

> Clover still needs the UEFI BIOS boot menu to be invoked first
I don't know what means : Clover finds UEFI Bios boot menu.

> w/o detour
No idea what is that "detour".


> What about on our hack if you run `ControlMsrE2.efi` from `Tools` in Clover?
Something like : "register not found". I'm not even sure what is MsrE2, but I don'thave that, I think.

**Comment by LeeBinder** [comment]
jief, thanks for being willing to dig even deeper into this, but if all this does not tell you anything, it's OK to just forget about it - it's fine enough now the way it is after your corrections. The extra step with having to enter the UEFI boot menu before running Clover for MSR E2 register detection and flipping the bit might just be an Asus Vivobook S15 oddity, so we can simply let it slide for now. I'd say it might help more Clover users to rather focus on the other issues here :)
